apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: volosoft-eventhub-httpapi-host-static
  namespace: ingress-basic
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  rules:
  - host: https://openeventhub.com/
    http:
      paths:
      - backend:
          service:
            name: volosoft-eventhub-identityserver-service
            port: 
              number: 80
        path: /static(/|$)(.*)

