apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityserver
spec:
  selector:
    matchLabels:
      app: identityserver
  template:
    metadata:
      labels:
        app: identityserver
    spec:
      containers:
      - name: identityserver
        image: eventhubregistry.azurecr.io/eventhubregistry:v3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80