apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpapi-host
spec:
  selector:
    matchLabels:
      app: httpapi-host
  template:
    metadata:
      labels:
        app: httpapi-host
    spec:
      containers:
      - name: httpapi-host
        image: eventhubregistry.azurecr.io/eventhubregistry:v2
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80